# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(max_length=512)),
                ('category', models.CharField(blank=True, choices=[('-----', ''), ('Organiser', 'organiser'), ('Coach', 'coach'), ('Tutorial', 'tutorial')], max_length=512)),
            ],
            options={
                'ordering': ('credit', 'category'),
            },
        ),
        migrations.CreateModel(
            name='CreditReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('show_email_in_public', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, help_text='Link to the person (twitter or something else)', max_length=1024, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'CreditReceivers',
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credits.CreditReceiver'),
        ),
    ]
