# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditReceiver',
            new_name='Contributor',
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ('name',), 'verbose_name_plural': 'Contributors'},
        ),
    ]
