# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20161105_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='github_login',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
